### PR TITLE
Ordering fix comparejson

### LINKED ISSUE #17: The tests for this package are flaky
As I pointed out in #16   since there are many possible arrangements in the output possible for a given pair of json of which we are trying to get the diff output for, thus it seems that the tests for this package do not have the exhaustive list of hashes for certain pairs of json's whose diff are being computed and thus the the flaky nature.

### PR DESCRIPTION
**Pull request by harshitashankar**
Tests were failing intermittently because Go's map iteration order is random by design, which meant that the order of nested objects could vary between runs. By sorting the keys before iteration, we can ensure consistent order that matches the test's expectations.

Fixes https://github.com/keploy/jsondiff/issues/17, https://github.com/keploy/jsondiff/issues/16

### CODE REVIEW

File: jsondiff.go [hunk 1]
```diff
@@ -824,8 +824,16 @@ func compareAndColorizeMaps(a, b map[string]interface{}, indent string, red, gre
 	expectedOutput.WriteString("{\n")                // Start the expected output with an opening brace and newline.
 	actualOutput.WriteString("{\n")                  // Start the actual output with an opening brace and newline.
 
-	// Iterate over each key-value pair in the first map.
-	for key, aValue := range a {
+	// Get all keys and sort them
+	keys := make([]string, 0, len(a))
```
Comment (Hermione2408) [inline jsondiff.go:828]: This key collection and sorting logic is repeated in multiple places. Consider extracting it into a helper like sortedKeys , You can reuse it for both a and b.

**Review by Hermione2408 — CHANGES_REQUESTED** [review]

**Comment by Hermione2408** [comment]
@harshitashankar, can you please send me the sample app with which you tested this change.
Also, we do have IgnoreOrdering flag in keploy open source which would ignore the ordering of the json map

File: jsondiff.go (hunk 1 above)
Comment (harshitashankar) [reply jsondiff.go:828]: Thanks for pointing out. However, in this case, I believe keeping the current implementation is more appropriate because the two places where we are sorting collections serve different purposes:
   - First case is a straightforward "get and sort" operation
   - Second case involves additional logic (checking for non-existence in map 'a') before sorting

Sort part is common in them where we are already using `sort.Strings(extraKeys)`. 

Combining these into a helper would actually make the code less clear 
Let me know if you'd like to discuss this further!

**Comment by harshitashankar** [comment]
> @harshitashankar, can you please send me the sample app with which you tested this change. Also, we do have IgnoreOrdering flag in keploy open source which would ignore the ordering of the json map

Verified using this UT- https://github.com/keploy/jsondiff/blob/main/jsonDiff_test.go#L677-L691
Reg ignoreOrdering flag - I checked this. Looks like ignore-ordering flag is not used in the jsondiff comparision.
I could find only one usage of this flag which was here
https://github.com/keploy/keploy/blob/main/pkg/matcher/utils.go#L943
its not being passed to interactions with jsondiff

Let me know if you think something else also needs to be tested.

File: jsondiff.go (hunk 1 above)
Comment (Hermione2408) [reply jsondiff.go:828]: That makes sense, thanks for the clarification!
I raised it mostly from a reusability/readability lens since the sorting pattern was visually repeated, but agree that extracting it may overcomplicate a small and localized pattern here.

**Comment by Hermione2408** [comment]
It looks good to me!
